version = 0.1
[default.deploy.parameters]
stack_name = "yolo-prod"
resolve_s3 = true
s3_prefix = "yolo-prod"
region = "us-east-1"
profile = "default"
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=230575066025.dkr.ecr.us-east-1.amazonaws.com/yoloprod61ab2b6b/inferencefunction7c73919drepo", "ProcessImageLambda=230575066025.dkr.ecr.us-east-1.amazonaws.com/yoloprod61ab2b6b/processimagelambdafb51752crepo", "RecognitionLambda=230575066025.dkr.ecr.us-east-1.amazonaws.com/yoloprod61ab2b6b/recognitionlambdad5faa89drepo"]
