AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 900
    MemorySize: 5000

Resources:
  DeadLetterQueueTest:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ImageQueueDLQTest

  ImageQueueTest:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ImageQueueTest
      VisibilityTimeout: 910
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueueTest.Arn
        maxReceiveCount: 5

  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Inference:
          Type: Api
          Properties:
            Path: /detect
            Method: post
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ImageQueueTest.QueueName
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource: arn:aws:s3:::*/*
      Environment:
        Variables:
          QUEUE_URL: !Ref ImageQueueTest

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./fetch_image
      DockerTag: python3.11-v1

  ProcessImageLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ImageQueueTest.Arn
            BatchSize: 1
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt ImageQueueTest.QueueName
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource: arn:aws:s3:::*/*
        - Statement:
            Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
              - ec2:AttachNetworkInterface
            Resource: '*'
      VpcConfig:
        SecurityGroupIds:
          - sg-0b459a3965993b898
        SubnetIds:
          - subnet-3a7e5a5d
      Environment:
        Variables:
          MONGO_URL: "mongodb+srv://mrunal-p360:qLekk9TJHctxgrmm@cluster0.zevqw.mongodb.net/proctor360?authSource=admin&replicaSet=atlas-s7hf6n-shard-0&readPreference=primary&ssl=true"
      
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.11-v1

  ProcessImageLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ProcessImageLambda

  ProcessImageLambdaProvisionedConcurrency:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ProcessImageLambda
      FunctionVersion: !GetAtt ProcessImageLambdaVersion.Version
      Name: Provisioned
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 10

  InferenceFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref InferenceFunction

  InferenceFunctionProvisionedConcurrency:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref InferenceFunction
      FunctionVersion: !GetAtt InferenceFunctionVersion.Version
      Name: Provisioned
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 10

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  InferenceApi:
    Description: API Gateway endpoint URL for Prod stage for Inference function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/detect/
  InferenceFunction:
    Description: Inference Lambda Function ARN
    Value: !GetAtt InferenceFunction.Arn
  InferenceFunctionIamRole:
    Description: Implicit IAM Role created for Inference function
    Value: !GetAtt InferenceFunctionRole.Arn
  ProcessImageLambdaFunction:
    Description: Process Image Lambda Function ARN
    Value: !GetAtt ProcessImageLambda.Arn
  DeadLetterQueueUrl:
    Description: Dead Letter Queue URL
    Value: !Ref  DeadLetterQueueTest
